name: CI


on:
  push:
    paths: 'api/**'
  pull_request:
    branches: [ 'main' ]


jobs:
  build:
    defaults:
      run:
          working-directory: './First-app/first-app'
    
    runs-on: ubuntu-latest
      
    steps:
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.1-rc.0
        with:
          working-directory: './First-app/first-app'
