name: CI


on:
  push:
    paths: 'api/**'
  pull_request:
    branches: [ 'main' ]


jobs:
  build:
    defaults:
      run:
          working-directory: ./First-app/first-app
    
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./First-app/first-app/package-lock.json
          
          
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.1-rc.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./First-app/first-app/package-lock.json
          working-directory: ./First-app/first-app
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run lint
